#!/bin/bash

bold=$(tput bold)
normal=$(tput sgr0)

repo=${VASC_RELEASE_REPO:-"vadymcap/Vasc"}
current=$(curl "https://api.github.com/repos/${repo}/releases/latest" -s | grep -i "tag_name" | awk -F '"' '{print $4}')

if command -v pbcopy > /dev/null 2>&1; then
	echo "$current" | tr -d '\n' | pbcopy 2> /dev/null
elif command -v clip.exe > /dev/null 2>&1; then
	echo "$current" | tr -d '\n' | clip.exe > /dev/null 2>&1
fi

echo Current vasc version is: ${bold}$current${normal}
echo

read -p "Enter a new version to release: " version
echo

read -p "Is this version correct: ${bold}$version${normal} [y/n] " confirm 
echo

if [ "$confirm" != "y" ]; then
	echo Aborted!
	exit 1
fi

echo Releasing version ${bold}$version${normal} ...

git tag $version && git push --tags
